---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config-bgp
data:
  config: |
    peers:
    - peer-address: 10.0.30.1
      peer-asn: 64501
      my-asn: 64500
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.0.30.10-10.0.30.50
      avoid-buggy-ips: true
