version: '3'

services:
  postgress:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    security_opt:
      - no-new-privileges:true
    volumes:
      - $HOME/postgres/data:/var/lib/postgresql/data