apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-harbor
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-harbor
    namespace: services
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.10.10
    path: "/mnt/vault/Kubernetes/harbor"
