---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-harbor
  namespace: services
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-harbor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
