# Home Assistant integration (MQTT discovery)
homeassistant: true
# Let new devices join our zigbee network
permit_join: true
# Docker-Compose makes the MQTT-Server available using "mqtt" hostname
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.10.252:1881
  user: 
  password: 
# Zigbee Adapter path
serial:
  port: /dev/ttyACM0
  adapter: deconz
# Enable the Zigbee2MQTT frontend
frontend:
  port: 8081
  url: 'https://zigbee2mqtt.local.technolab.cloud'
# Let Zigbee2MQTT generate a new network key on first start
advanced:
  network_key: GENERATE