version: "3"

services:
  grafana:
    image: grafana/grafana:8.4.4
    container_name: grafana
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - monitoring
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=technolab.cloud
    volumes:
      - $HOME/grafana/data:/var/lib/grafana

networks:
  monitoring:
    external: true