---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: services
data:
  configuration.yml: |
    ###############################################################
    #                   Authelia configuration                    #
    ###############################################################

    # The host and port to listen on
    server:
      host: 0.0.0.0
      port: 9091
      read_buffer_size: 4096
      write_buffer_size: 4096

    log:
      level: debug
      format: json

    # jwt_secret: ${JWT_SECRET}

    theme: dark

    default_redirection_url: https://technolab.cloud

    totp:
      issuer: authelia.com

    authentication_backend:
      disable_reset_password: true
      refresh_interval: 5m
      ldap:
        url: ldap://ldap.local.technolab.cloud:389
        start_tls: false
        base_dn: dc=technolab,dc=cloud
        username_attribute: uid
        additional_users_dn: ou=users
        users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
        additional_groups_dn: ou=groups
        groups_filter: (&(member={dn})(objectclass=groupOfNames))
        group_name_attribute: cn
        mail_attribute: mail
        display_name_attribute: displayName
        user: cn=admin,dc=technolab,dc=cloud
        # password: ${LDAP_ADMIN_PASSWORD}

    access_control:
      default_policy: deny
      rules:
        - domain: codeserver.technolab.cloud
          subject: "user:ebrianne"
          policy: two_factor
        - domain: bitwarden.technolab.cloud
          subject: "user:ebrianne"
          policy: two_factor
        - domain: bitwarden.technolab.cloud
          subject: "user:mengqing"
          policy: two_factor
        - domain: technolab.cloud
          resources:
          - "^/whoami"
          subject: "user:ebrianne"
          policy: one_factor

    session:
      name: authelia_session
      # secret: ${SESSION_SECRET}
      expiration: 24h
      inactivity: 1h
      remember_me_duration: 24h
      domain: technolab.cloud

      redis:
        host: redis-headless.redis.svc.cluster.local
        port: 6379
        # password: ${REDIS_PASSWORD}
        database_index: 0
        maximum_active_connections: 8
        minimum_idle_connections: 0

    regulation:
      max_retries: 5
      find_time: 2m
      ban_time: 10m

    storage:
      # encryption_key: 
      postgres:
        host: 10.0.30.12
        port: 5432
        database: authelia
        username: authelia
        # password: ${DB_PASSWORD}
        sslmode: disable

    notifier:
      disable_startup_check: true
      # filesystem:
      #   filename: /config/notification.txt
      smtp:
        # username: ebrianne
        # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
        # password: ${SMTP_PASSWORD}
        host: 192.168.10.50
        port: 1025
        sender: authelia@home-lab.io
        # HELO/EHLO Identifier. Some SMTP Servers may reject the default of localhost.
        identifier: authelia
        # Subject configuration of the emails sent.
        # {title} is replaced by the text from the notifier
        subject: "[Authelia] {title}"
        # This address is used during the startup check to verify the email configuration is correct. It's not important what it is except if your email server only allows local delivery.
        startup_check_address: test@home-lab.io
        disable_require_tls: true
        disable_html_emails: false
