---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia-auth
  namespace: services
spec:
  forwardAuth:
    address: http://authelia.services.svc.cluster.local/api/verify?rd=https://authelia.technolab.cloud/
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia-headers
  namespace: services
spec:
  headers:
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "same-origin"
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlMaxAge: 100
    hostsProxyHeaders:
      - "X-Forwarded-Host"
    sslRedirect: true
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    customResponseHeaders:
      Cache-Control: "no-store"
      Pragma: "no-cache"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-real-ip
  namespace: services
spec:
  plugin:
    traefik-real-ip:
      excludednets:
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: services
spec:
  rateLimit:
    sourceCriterion:
      ipStrategy:
        depth: 2
    burst: 50
    average: 100
    period: 5s
