---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  minAvailable: 1