---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: kube-system
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.30.10
  ports:
    - name: websecure
      port: 443
      protocol: TCP
      targetPort: websecure
    - name: git-ssh
      port: 10222
      protocol: TCP
      targetPort: git-ssh
  selector:
    app.kubernetes.io/name: traefik
  type: LoadBalancer
