---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-git
  namespace: services
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-git
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
