---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ssh-tcp-route
  namespace: services
  labels:
    app.kubernetes.io/name: gitea
spec:
  entryPoints:
    - git-ssh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: gitea
          port: 10222
