version: "3"

services:
  ombi:
    image: linuxserver/ombi:version-v4.10.2
    container_name: ombi
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - media
    ports:
      - 3579:3579
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=America/Chicago
    volumes:
      - $HOME/ombi/data:/config

networks:
  media:
    external: true
