---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer-production
spec:
  acme:
    email: eldwan35@gmail.com
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: cloudflare-issuer-account-token-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: eldwan35@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - 'technolab.cloud'
