version: "3"

services:
  calibre-web:
    image: linuxserver/calibre-web:version-0.6.17
    container_name: calibre-web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - $HOME/calibre-web/config:/config
      - $HOME/calibre-web/books:/books