apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secrets
  namespace: redis
spec:
  encryptedData:
    redis-password: AgA2C8cxlflPwXZAYwepfp4YHOEC71/lgoK8kTk1G5H0pWcbNQSx/nuASfm4Esu5cZ0CSXK9Y4smTtTsfmTwFjvNxD5R8bZKjyBAYB81SKP9V+85DYA0L93SOZDVJKN48tEon/wWPco/34zspVd9eXc50Ivr6PvNvmmoZ+A4IGjBNCD9lNEyx1LX65VU/mKCYRHVglcFrC8j7OJGFB5bCOgHhDo7/Qo9OcntjeFvE/lNAtpFZ9A0APwL06HYj+O7VZayZOZznK3PgRxoipoSjXnzzb1jnwq2iyW8fCdz5ble9JSNo4OiK/cJ3HrJDM6JzJ8xxk6vP9M/+YTpyEDjkaBE9TLrZnwtEmBsLFVc1bt0jpUdMChGtglmeQGwaWd5IX8xXCTRziGMHkztnfzOiCfLsxwsHOYamsmNgJmYsPqoZUu0gdFBtEPZ4xz6rrESaBSJ26KBZUSNtrdWq6aGvZgq888HIYT652KQMxXsgkvlPjUvnPH9g0ZlNhcjr5qj5TONxrI/5lliEkWOljXvlUpizCF0vxHasvpd2SV3JAvGbAIjN3NtlGKHdDHkqL3fwYP4w2Kh+Rk8X1P5phcxFkjXmHeeJgimhx1mQDeRzFaOhCrcHp0G7RsPLHSWWdsKUOixXji5Y3GBimRBW0MrCL4cvTUMxojL8kLdk2yD2G+dhqGT0sDHLOX5rEVHBMI8HzhYT4Yf5NX+Zq7TMfghNWX491JTE9vgNtrj3reqaobEoQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: redis-secrets
      namespace: redis
    type: Opaque

