---
redis:
  image:
    registry: docker.io
    repository: bitnami/redis
    # tag: 6.2.3-debian-10-r0
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false

  ## @param architecture Redis(TM) architecture. Allowed values: `standalone` or `replication`
  ##
  architecture: standalone

  auth:
    enabled: true
    sentinel: false
    existingSecret: redis-secrets
    existingSecretPasswordKey: redis-password
    usePasswordFiles: true

  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""

  master:
    disableCommands:
      - FLUSHDB
      - FLUSHALL

    persistence:
      enabled: true
      existingClaim: nfs-pvc-redis

  sentinel:
    enabled: false

  networkPolicy:
    enabled: false
    allowExternal: true

  podSecurityPolicy:
    create: false

  rbac:
    create: false

  serviceAccount:
    create: true

  pdb:
    create: false

  tls:
    enabled: false

  metrics:
    enabled: false

  volumePermissions:
    enabled: false

  sysctl:
    enabled: false
