version: "3"

services:
  homer:
    image: b4bz/homer:22.02.1
    container_name: homer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 8080:8080
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - $HOME/homer/data:/www/assets

