---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: kured
spec:
  project: default

  source:
    repoURL: https://github.com/romelBen/k3s-home-projects.git
    targetRevision: HEAD
    path: k3s/apps/kured/
    helm:
      releaseName: kured
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kured

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
