version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    container_name: mosquitto
    networks:
      - ha_net
    ports:
      - 1883:1883
    volumes:
      - $HOME/mosquitto/data:/mosquitto/data
      - $HOME/mosquitto/logs:/mosquitto/logs
      - $HOME/mosquitto/config:/mosquitto/config
    restart: unless-stopped

networks:
  ha_net:
    external: true