---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-system-technolab-cloudflare-org
  namespace: kube-system
spec:
  dnsNames:
  - '*.technolab.cloud'
  - 'technolab.cloud'
  issuerRef:
    name: cloudflare-issuer-production
    kind: ClusterIssuer
  secretName: kube-system-technolab-cloudflare-org-tls
