---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: services-technolab-cloudflare-org
  namespace: services
spec:
  dnsNames:
  - '*.technolab.cloud'
  - 'technolab.cloud'
  issuerRef:
    name: cloudflare-issuer-production
    kind: ClusterIssuer
  secretName: services-technolab-cloudflare-org-tls
