---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-code-server
  namespace: services
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-code-server
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
