apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: code-server-secret
  namespace: services
spec:
  encryptedData:
    sudo_password: AgBCPtXO/QoWE7o/5ewHVcQ2koI7h4WwtlkZdITSNcz5GVyC4zurUsar6dl7t4uBuXWknpXJ9CHsY6oHKOAR9iuT5X01xDWRSWGfg3Hp/afnr5RuCnhxW+nbAncJRFWpakPPgkfKwH3rthZBoa3BP5DmDKJCpfNMOwVk5wRNGgpKOleR2kmDVt2W9EYdB2MpFJkNufhGzhMO1n4ek1HzYXRYNGOrNmq+DEji8/ms+SCVy7lR1OfsE14e9QWvXsJMaqL8ltU2lXhF+IdbA9vzipIUt7Ei5eQN39Ibztftk2vvANf5ce9x/YECIPYwPPIOD1nfnFc5/HSdMHAbkNEfk5O6bEbLqN3ar+0b+CCmqgWmXwZfZ0bUN0hzZsqQRHeI8Y7JdIZ/355n5Sr8Pd96Ffm8aqMI083EH5ct42BcWc6PmMeePwdUiTjatQzGsXbCPkyslXbHz2dnNLMYMt9lKNZCtWYGnycsp0tZ3eN+SZSGg/EjGZAgJm/lJr7hkEJqHURZzOQnxFg09pPABDDtAIqo9hXIjHlWlgibXtLCxsnAE5AUIopAkBfqg5MlsbXrPHueXnUizB8AmttsniAB+6k0rFFlBlxTBVID7fWWbCw02MBs6CPlxeEYTTXQG63gOScziY2NNYznww+ex2EAq4QaSmYumEjJIVMD9sW+Xxg+8G1DTx8Foa2KfXf+iPeOJtceIoN8tMUjeDuLsmuO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: code-server-secret
      namespace: services
    type: Opaque

