version: "3"

services:
  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    volumes:
      - $HOME/loki/data:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - monitoring

networks:
  monitoring:
    external: true