---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: services
  labels:
    app: whoami
  annotations:
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: whoami
