---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-postgres
  namespace: database
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
