apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    postgres-password: AgBvzHcuaayH5wEwOc03FZs2mMS/fU1f3D3KL9dNAreFXnAt81ecyFjOB9moFeZemzfA/MgQCvvA4yZYukFmYFQxQ+EEjnw2q7F4b1a51BgOD5buj38XvQRouhZ7Dj44nf0x7VfPCRxPD8Y/DmsbL1t0G10CDuSfljW9BXAemX8h/rjF6d45WNYuERsJ+9lPE4bOX+x8wXfd/7sSm1fWYQO1v1ov3G36c8P4vY5OopUUanahQW93wvuk2iWpDSrTERIfmHwQ8blb2rAkdhSA8GoSvUzNDFUe5slxbvxRIQQgg0KsFJDfhUzqY3s9H+YwKja4GPNuFp5plckwUy9QVY8MRJ1vyEAm4Cef7pfufE5LyFhMBKQ4ORQIwyRzDfP9sEXXxQxOnQQjpTKgc4ddu8Y8AlHs78LQW0ezH3T2iwfYmGXY4wjZNfyCHCtgyQfMxksfnrlpi2MRPW6nl4azbD8iKtPt7bOhOVdXz6Rvvg65FzdBy41e2ZPraKSr8FM7agF390FnsaJWAtiSRXuG7QPoHxu4CRTPNd+WrFGR1RjnlERo9z9SLRArz/qmWFpfijn1S+IarTWyNAIOELzwybZZKsIEZxZ6a9CcMT9UGzoOx1UJ7pgxxS2IynrGoiUU7+doSZ3sIbpWBoH0DQaBRds64VH9Nnl2egAUx7WnO/lN3hBd0koU+V6Cas3EwOM7HTc24CZsVucI1My4ZACR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: database
    type: Opaque

