---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
  namespace: database
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.30.12
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
