version: '3'

services:
  portainer-agent:
    image: portainer/agent:2.12.1-alpine
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - $HOME/portainer-agent/data:/data
    environment:
      - EDGE=1
      - EDGE_ID=
      - EDGE_KEY=
      - CAP_HOST_MANAGEMENT=1
      - EDGE_INSECURE_POLL=1