version: "3"

services:
  promtail:
      image: grafana/promtail:2.4.2
      container_name: promtail
      volumes:
        - /var/log:/var/log
        - $HOME/promtail/data:/etc/promtail
      ports:
        - 1514:1514
      restart: unless-stopped
      command: -config.file=/etc/promtail/promtail-config.yml
      networks:
        - monitoring

networks:
  monitoring:
    external: true