---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: metrics-server
spec:
  project: default

  source:
    repoURL: https://github.com/romelBen/k3s-home-projects.git
    targetRevision: HEAD
    path: k3s/apps/kube-system/metrics-server
    helm:
        releaseName: metrics-server
        valueFiles:
          - values.yaml
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
