---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: whoami
spec:
  project: default

  source:
    repoURL: https://github.com/romelBen/k3s-home-projects.git
    targetRevision: HEAD
    path: k3s/apps/services/whoami/

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
