version: '3'

services:
  influxdb:
    image: influxdb:2.1.1-alpine
    container_name: influxdb
    volumes:
      - $HOME/influxdb/data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    restart: unless-stopped
    