---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo-cd
  name: system-upgrade-controller
spec:
  project: default

  source:
    repoURL: https://github.com/romelBen/k3s-home-projects.git
    targetRevision: HEAD
    path: k3s/apps/system-upgrade/

  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
