---
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: authelia
spec:
  forceHttps: true
  providers: "UptimeRobot"
  url: https://authelia.technolab.cloud/
  uptimeRobotConfig:
    interval: 300
    monitorType: "keyword"
    keywordExists: "yes"
    keywordValue: "404"
