version: "3"

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    container_name: prometheus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - $HOME/prometheus/config:/etc/config
      - $HOME/prometheus/data:/data
    command:
      - '--storage.tsdb.retention.time=1h'
      - '--config.file=/etc/config/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--storage.tsdb.wal-compression'

networks:
  monitoring:
    external: true