apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-bitwarden
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-bitwarden
    namespace: services
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.10.10
    path: "/mnt/vault/Kubernetes/bitwarden"
