---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-bitwarden
  namespace: services
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-bitwarden
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
