apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgArCeyHoLhO1jyW8K+nTHmXIbHOE6wyIhy6Jzio2wS61DSDBAszNNMI9orFyaVx+0V0430MN2rWGdUVSESnGZl68cDBH6ZSy8mqrCut9vdoY5kKLWOz2HgKxpQGeM5mF9VOJqjKyfIl6P0Ch4cbpHz01XWmKSopX9QLUvAxou8nFF5gr7gXEP/PVfBOgbNgtG164ourpOjYa9zTy4bsJ8uPkGX2j32g6Uz18PlpmOl9xjFB1MKnQ6Us5DeU2J+W1GCRkqF4n7lWAcAUWFQ5XKgRJFu9kGVmBKp9XFS87KGBVt5oAuinUoNy68hZMXSoqPUnyqyBSDw6HPOS/VMHg7VWg0a6ifqwW5VIIAp8rDH08zV0Bab7F/fLMb7jz/W/CGFybFaAKfu5XJhxRct8G2z+29zxlkfaVgWVXyCUcsYYt/r7TakTypzjSAfbXrbUINRd7WLp9PaBNeGNFxPVm6CNrcOkT5dYQmtq7Jay6+8FsyVKgl59pOHquCDBCWH6YPmD3EeV9R/DDJxRLZV+QulTUF29csdLgZnTDBMBPYK5sYKd6PERMJRHyDjch6TxwsPEWrCbFaJVCJhvMT+kvYp4GfjdyjZy2o/HRgL1LuGDtg8zfsFvlm5DpurSWLuL28UsPV0AYy9KrE/hWEOoQGhCCOO2Gbdx8SAKEUwtO4FsXGUB+5g0w79ZMT/axvtwnVIa6Nf49s7vvhzrL8nG+Bht6KyjsB2HxLQbYHgrjetRjnzdoNRqoywy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

