cert-manager:
  installCRDs: true

  extraArgs:
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
    - --dns01-recursive-nameservers-only

  podDnsPolicy: "None"
  podDnsConfig:
    nameservers:
      - "1.1.1.1"
      - "8.8.8.8"
