apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nextcloud
spec:
  storageClassName: ""
  claimRef:
    name: nfs-pvc-nextcloud
    namespace: services
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.10.10
    path: "/mnt/vault/Kubernetes/nextcloud"
