---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-nextcloud
  namespace: services
spec:
  storageClassName: nfs-client
  volumeName: nfs-pv-nextcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
