version: "3"

services:
  unifi:
    image: linuxserver/unifi-controller:7.0.23
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M 
      - MEM_STARTUP=1024M 
    volumes:
      - $HOME/unifi/data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp 
      - 8843:8843 
      - 8880:8880
      - 6789:6789 
      - 5514:5514/udp
    restart: unless-stopped