global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 5m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'adguard'
    static_configs:
      - targets: 
        - 192.168.10.252:9617
  
