version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.12.1-alpine
    container_name: uptime-kuma
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 3001:3001
    environment:
      - TZ=America/Chicago
    volumes:
      - $HOME/uptime-kuma/data:/app/data