---
apiVersion: v2
name: metrics-server
type: application
version: 3.7.0
appVersion: 0.5.2
dependencies:
  - name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.8.2