---
apiVersion: v2
type: application
name: descheduler
version: 0.20.0
appVersion: 0.20.0
dependencies:
  - name: descheduler
    repository: https://kubernetes-sigs.github.io/descheduler
    version: 0.23.2
