name: Check Kubernetes YAMLs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan repo
        id: kube-lint-repo
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: apps
          #config: .kube-linter/config.yaml